---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Nginx-cluster
  region: us-east-1

vpc:
  id: "vpc-0b1aca68fd4cd169d"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: "subnet-065f318450ec070c2"
        cidr: "172.31.0.0/20"

      us-east-1c:
        id: "subnet-05f8e5caca5b10498"
        cidr: "172.31.16.0/20"

    private:
      us-east-1b:
        id: "subnet-00808a0d6f63b4cde"
        cidr: "172.31.64.0/28"

      us-east-1d:
        id: "subnet-05aa5c31ed3abe2c7"
        cidr: "172.31.32.0/20"

managedNodeGroups:
  - name: managed-NG-public
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    subnets:
      - subnet-065f318450ec070c2
      - subnet-05f8e5caca5b10498
    volumeSize: 20
    updateConfig:
      maxUnavailable: 1
    securityGroups:
      attachIDs: ["sg-0184afd669d60b043"]
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

  - name: managed-ng-private
    instanceType: m5.large
    # launch nodegroup in private subnets
    privateNetworking: true
    subnets:
      - subnet-00808a0d6f63b4cde
      - subnet-05aa5c31ed3abe2c7
